# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/dist/CowCat_Node
    overwrite: true

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 120
      runas: ec2-user
  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 50
      runas: ec2-user
  ValidateService:
    - location: scripts/validate_server.sh
      timeout: 30
      runas: ec2-user