# This is a basic workflow to help you get started with Actions

name: Deploy to Production

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
     name: Build, Deploy to S3 Bucket
     runs-on: ubuntu-latest
     
     strategy:
       matrix:
         node-version: [15.10.x]
     
     steps:
       - uses: actions/checkout@v2
       
       - name: Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
          node-version: ${{ matrix.node-version }}

       - name: Npm install
         run: npm install
      
       - name: lint
         run: npm run lint
         env:
            CI: true
